name: "Deploy Preview Environment"

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build_job.yml

  deploy:
    uses: ./.github/workflows/deploy_job.yml
    secrets: inherit
    needs:
      - build
    with:
      environment: "Preview"
