name: "Release"

on:
  release:
    types:
      - released

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build_job.yml

  deploy:
    uses: ./.github/workflows/deploy_job.yml
    needs:
      - build
    secrets: inherit
    with:
      environment: "Production"
