name: "Build"

on:
  workflow_call:

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Setup stack and build binary"
        uses: freckle/stack-action@v5
        with:
          stack-build-arguments-build: --copy-bins

      - name: "Upload binary"
        uses: actions/upload-artifact@v4
        with:
          name: "bootstrap"
          path: ~/.local/bin/bootstrap
